from abc import ABC, abstractmethod
from enum import StrEnum
from collections.abc import AsyncGenerator

from pydantic import BaseModel

from conversational_toolkit.tools.base import Tool


class Roles(StrEnum):
    SYSTEM = "system"
    USER = "user"
    ASSISTANT = "assistant"
    TOOL = "tool"
    DEVELOPER = "developer"


class Function(BaseModel):
    name: str
    arguments: str


class ToolCall(BaseModel):
    id: str
    function: Function
    type: str


class LLMMessage(BaseModel):
    content: str = ""
    role: Roles = Roles.ASSISTANT
    tool_calls: list[ToolCall] | None = None
    tool_call_id: str | None = None
    name: str | None = None


class LLM(ABC):
    def __init__(self) -> None:
        self.tools: list[Tool] | None = []

    @abstractmethod
    async def generate(self, conversation: list[LLMMessage]) -> LLMMessage:
        """
        Generates a response based on the provided conversation.

        Parameters:
        conversation (list[LLMMessage]): A list of messages

        Returns:
        str: The response generated by the model.
        """
        pass

    @abstractmethod
    def generate_stream(self, conversation: list[LLMMessage]) -> AsyncGenerator[LLMMessage, None]:
        pass
